KangManJoo 22/12/16 5522 submit
MinboyKim/BojAlgorithmStudy pull request #107
Opened 2022-12-16 07:51 UTC by eogns47

슬슬 관성이 위험하다..

2022-12-16 07:52 UTC, MinboyKim requested changes

2022-12-16 07:52 UTC, MinboyKim commented on 22_December/14/README.md
>  ##9654번 - [나부항성 데이터](https://www.acmicpc.net/problem/9654)
문제번호도 대괄호 안에 넣고 난이도 추가해주세요

2022-12-16 13:06 UTC, kwan7595 approved these changes
골드로 돌아와

2022-12-17 08:22 UTC, eogns47 commented on 22_December/14/README.md
>  ##9654번 - [나부항성 데이터](https://www.acmicpc.net/problem/9654)
하잇

2022-12-17 08:22 UTC, merged