KangManJoo 23/1/8 1504 submit
MinboyKim/BojAlgorithmStudy pull request #166
Opened 2023-01-08 08:22 UTC by eogns47

드디어 골드 등반!!
다익스트라까지 완료했으니 당분간 그래프는 접어두고 다시 오문추로 복귀,,

2023-01-08 08:50 UTC, eogns47 commented
묵혀왔던 10942번 까지 완료,, 이게 골드의 힝께끼?

2023-01-09 03:12 UTC, MinboyKim requested changes

2023-01-09 03:12 UTC, MinboyKim commented on 23_January/8/10942_KangManJoo.cpp
> +			solve1(x + 1, 0);      //����� ������� �Ӹ������ ������� ��
주석이거 한글로 써서 이래 보이나?

2023-01-09 03:12 UTC, MinboyKim commented on 23_February/8/README.md
> +## [1504번 - 특정한 최단 경로 GOLD IV](https://www.acmicpc.net/problem/1504)
10942번은 외않씀

2023-01-09 03:13 UTC, MinboyKim commented
골드 ㅊㅊㅊ

2023-01-09 08:12 UTC, eogns47 commented on 23_January/8/10942_KangManJoo.cpp
> +			solve1(x + 1, 0);      //����� ������� �Ӹ������ ������� ��
ㄷㄷ 그런듯 노션에서 확인 ㄱㄱ

2023-01-09 08:12 UTC, eogns47 commented on 23_February/8/README.md
> +## [1504번 - 특정한 최단 경로 GOLD IV](https://www.acmicpc.net/problem/1504)
썻는데 왜 사라졋노

2023-01-09 08:47 UTC, kwan7595 approved these changes
골드 축하용

2023-01-09 08:47 UTC, kwan7595 commented on 23_January/8/10942_KangManJoo.cpp
> +			solve1(x + 1, 0);      //����� ������� �Ӹ������ ������� ��
주석은 영어로 다는 습관을...

2023-01-09 08:48 UTC, merged